### ISSUE TITLE
[IOS] set bottomSheetColor error

### ISSUE THREAD

**Issue by torbenkeller** [Daniel-Ioannou/flutter_adaptive_action_sheet#10]
When setting the bottomSheetColor, the transparent shadow will be replaced by this color on IOS

**Comment by Daniel-Ioannou** [comment]
I fix the issue with the transparent shadow. `barrierColor` and `backgroundColor` is only for Android `showCupertinoModalPopup` doesn't support `barrierColor` or `backgroundColor`. Check more for [here](https://github.com/flutter/flutter/issues/50604) and in the [documentation](https://api.flutter.dev/flutter/cupertino/showCupertinoModalPopup.html).
If you have another solution feel free to open pull request.
