### ISSUE TITLE
Missing functionality showing icon and changing text position 

### ISSUE THREAD

**Issue by guyluz11** [Daniel-Ioannou/flutter_adaptive_action_sheet#13]
It will be nice to have the option to show icon along side the text and to be able to change text location to the left  or right.

Image for example
![image](https://user-images.githubusercontent.com/9304740/104525307-8b327900-5608-11eb-867c-13a939d3d15a.png)

**Comment by guyluz11** [comment]
(Emoji is not a good solution) 

![image](https://user-images.githubusercontent.com/9304740/104527415-57a61d80-560d-11eb-9d7e-83d04f016a8c.png)

**Comment by Daniel-Ioannou** [comment]
It was in my plans to do it, but I did not have time. I will start working on it this weekend.

**Comment by Daniel-Ioannou** [comment]
### In v1.0.11:
* Add options for leading and trailing widget
* Add options for text align
  ```Dart
  showAdaptiveActionSheet(
    context: context,
    actions: <BottomSheetAction>[
      BottomSheetAction(
        title: 'Add',
        onPressed: () {},
        leading: const Icon(
          Icons.add,
          size: 25,
        ),
        trailing: const Icon(
          Icons.delete,
          size: 25,
          color: Colors.red,
        ),
        textAlign: TextAlign.start,
      ),        
    ],
    cancelAction: CancelAction(title: 'Cancel'),
  );
  ```
