### ISSUE TITLE
Minimal support for browser

### ISSUE THREAD

**Issue by guyluz11** [Daniel-Ioannou/flutter_adaptive_action_sheet#14]
Not having browser support lower this pacage sore.

I am not sure what layout would I expect for action bottom sheet.

Maybe small action sheet from the bottom center that does not take all the page width if it is bigger than x.

![Screenshot_20210114-125332_Firefox](https://user-images.githubusercontent.com/9304740/104581749-a97b9180-5667-11eb-847d-e11074f268f5.png)

**Comment by guyluz11** [comment]
Did a little digging and found out about [universal_io](https://pub.dev/packages/universal_io), it is like `dart.io` but can be used on [browser too](https://stackoverflow.com/questions/56945106/import-dartio-not-support-on-the-web-application).

So we can use `foundation.dart` to detect web if needed and use the  `universal_io` to detect IOS and Android without  lowering the package sore.

```
import 'package:flutter/foundation.dart' show kIsWeb;

if (kIsWeb) {
  // running on the web!
} else {
  // NOT running on the web! You can check for additional platforms here.
}
```

**Comment by guyluz11** [comment]
Sharing here testing with browser (code include pull request)

![image](https://user-images.githubusercontent.com/9304740/104586143-be5b2380-566d-11eb-9872-6bb74cfad3c1.png)
![image](https://user-images.githubusercontent.com/9304740/104586180-cfa43000-566d-11eb-8e56-22b4840054ec.png)
![image](https://user-images.githubusercontent.com/9304740/104586200-d6cb3e00-566d-11eb-94e8-0df2a56828c3.png)

**Comment by Daniel-Ioannou** [comment]
I am not sure what layout would I expect for web, I am more familiar with mobile app's design guidelines and components. I test your pull request and looks ok for now.
